# my global config
global:
  scrape_interval:     15s # Set the scrape interval to every 15 seconds. Default is every 1 minute.
  evaluation_interval: 15s # Evaluate rules every 15 seconds. The default is every 1 minute.
  # scrape_timeout is set to the global default (10s).

# Load rules once and periodically evaluate them according to the global 'evaluation_interval'.
rule_files:
# - "first_rules.yml"
# - "second_rules.yml"

# A scrape configuration containing exactly one endpoint to scrape:
# Here it's prometheus itself.
scrape_configs:
  # The job name is added as a label `job=<job_name>` to any time series scraped from this config.
  - job_name: 'prometheus'
    #override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    #If you are using docker to run prometheus monitoring tool, localhost will not work you can use your machine ip address. Otherwise, use localhost.
    static_configs:
      - targets: ['192.168.0.4:9090']

   #Configuration to connect prometheus with spring boot actuator(manage) endpoint to scrape the data
   # The job name is added as a label job=<job_name> to any time series scraped from this config.
  - job_name: 'bring_your_own_interview_springboot_app'
    #actuator(manage) endpoint to collect the data.
    metrics_path: '/manage/prometheus'
    # how frequently scrap the data from the endpoint
    scrape_interval: 5s
    # target endpoint. If you are using docker to run your spring boot /manage/prometheus application, localhost will not work, so you can use your machine ip address. My machine ip address is 192.168.0.4.
    # If you are not using docker, then you can use localhost
    static_configs:
      - targets: ['192.168.0.4:8081']
    basic_auth:
      username: 'admin'
      password: 'admin'